### ISSUE TITLE
Guarantee that prometheus disk is remounted after master VM reboot

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/k8s-support#101]
To monitor the k8s platform master we wish to run on prometheus instance on each k8s master VM.

Currently we are relying on an out-of-band allocation for the persistent volume and an ad-hoc mount point `/mnt/local` used by the Prometheus daemonset.

This mount point must be added to `/etc/fstab` so that the volume is mounted automatically after a reboot.

**Comment by nkinkade** [comment]
I believe this issue [should be resolved](https://github.com/m-lab/k8s-support/pull/102/files#diff-e05991c2911116f61acf8323abe8860eR216)  with this #102.

**Comment by nkinkade** [comment]
Confirmed resolved by #102. Closing.
