### ISSUE TITLE
Pod gets wrong network configuration and is not reachable

### ISSUE THREAD

**Issue by evfirerob** [m-lab/k8s-support#111]
This issue was first discovered on node `mlab4.par04`. 

The node was not getting any NDT test traffic. Trying to reach https://ndt-iupui-mlab4-par04.measurement-lab.org:3010/static/widget.html resulted in a timeout. Listing the interfaces from within the container showed a configuration that was significantly different than any other (working) NDT pod:

`ip addr`:
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: cni0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP qlen 1000
    link/ether 42:32:36:53:56:8f brd ff:ff:ff:ff:ff:ff
    inet 192.168.33.1/26 scope global cni0
       valid_lft forever preferred_lft forever
3: veth0a43e56a@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master cni0 state UP 
    link/ether 6e:40:6d:c1:1c:27 brd ff:ff:ff:ff:ff:ff
4: eth0@veth0a43e56a: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP 
    link/ether d2:71:a4:4a:27:93 brd ff:ff:ff:ff:ff:ff
    inet 192.168.33.33/26 scope global eth0
       valid_lft forever preferred_lft forever
5: vethbc48259b@net1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master cni0 state UP 
    link/ether a2:93:13:e9:3e:0d brd ff:ff:ff:ff:ff:ff
6: net1@vethbc48259b: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP 
    link/ether 16:39:b8:6f:58:98 brd ff:ff:ff:ff:ff:ff
    inet 192.168.33.3/26 scope global net1
       valid_lft forever preferred_lft forever
7: net2@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN 
    link/ether d2:71:a4:4a:27:93 brd ff:ff:ff:ff:ff:ff
    inet 77.67.119.178/26 scope global net2
       valid_lft forever preferred_lft forever
    inet6 2001:668:1f:6b::178/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::d271:a400:14a:2793/64 scope link 
       valid_lft forever preferred_lft forever
```

`brctl show`:
```bridge name	bridge id		STP enabled	interfaces
cni0		8000.42323653568f	no		veth0a43e56a
							vethbc48259b
```

In particular, the `veth` network interfaces are not present on a working NDT pod, and there is no bridge.

**Comment by nkinkade** [comment]
It appears that one of the core errors that the pod is logging in these cases is:

`error in invoke Delegate add - "flannel": failed to set bridge addr: "cni0" already has an IP address different from 192.168.4.65/26`

It would appear that flannel is refusing to set an IP address on the `cni0` interface because the interface already has one. In poking around, it appears that flannel (and other CNI plugins too, seemingly) can take a `forceAddress` option, which is false by default. I cannot find much official documentation about this option, but the few references I can find describe the flag like this:

> [forceAddress: Tells the plugin to allocate a new IP address if the previous value has changed.](https://www.dasblinkenlichten.com/understanding-cni-container-networking-interface/)

Perhaps if we set this option for the flannel delegate in the multus config, then this error will go away and things will start working as expected?

**Comment by nkinkade** [comment]
I have verified that m-lab/epoxy-images#92 resolves this issue. The ndt pod was stuck in "Init" phase on mlab4.par04. Manually modifying /etc/cni/net.d/multus-cni.conf on that node and adding the "forceAddress: true" option for the flannel delegate got the pod started without any other intervention on my part.

Closing issue.
