### ISSUE TITLE
Real metrics for native k8s node-exporter

### ISSUE THREAD

**Issue by nkinkade** [m-lab/k8s-support#122]
Currently our monitoring, and more importantly alerting, depends on certain node_exporter textfile metrics on nodes. These don't exist on the k8s platform. As a stop-gap we are synthetically creating static metrics via a ConfigMap for the purpose of squelching alerts.  This needs to be fixed with real replacement metrics and alerts.

**Comment by stephen-soltesz** [comment]
At the prometheus-sync we think that this can be addressed by removing the textfile and updating the related alerts to be node-version aware -- excluding new stack nodes that don't export certain metrics.

**Comment by stephen-soltesz** [comment]
@nkinkade Is this obsolete? Or are there specific metrics that we still need to update?

**Comment by nkinkade** [comment]
@stephen-soltesz: I _believe_ this is still a valid issue. Until we can [stop mounting the prometheus-synthetic-textfile-metrics ConfigMap](https://github.com/m-lab/k8s-support/blob/master/k8s/daemonsets/core/node-exporter.jsonnet#L153) and not receive collectd and vdlimit alerts, then this issue should probably still exist.

That said, instead of having real metrics for vdlimit and collectd, one strategy to get around this issue would be to add additional criteria to those legacy alerts that cause them not to fire if the node is part of the platform cluster. I seem to recall that we have used this strategy for some other alerts but can't recall which alerts at this moment.

Come to think of it, this should all get done sooner than later. I'll commit to adding these additional criteria to the alerts that would be affected by removing the synthetic textfile metrics this week.

Sound good?

**Comment by stephen-soltesz** [comment]
Do I understand correctly that we need two new metrics for the new platform:

* metrics for disco
* metrics for per-experiment disk utilization (which could just be whole disk-utilization initially)

And, a work item to update the existing alerts to incorporate these new metrics (assuming the names are different between old / new platforms).

Is this right?

**Comment by nkinkade** [comment]
* Metrics for DISCO: I'm assuming that we'll be running Disco/collectd as a DaemonSet on the platform cluster. If so, then the level of monitoring we currently have for collectd on the legacy platform should be easily replaced with same level of monitoring we have for all other existing DaemonSets. Nothing special will need to be done for the binary up/down and present/missing alerts we currently have.

* Metrics for per-experiment disk utilization: This would be a nice-to-have, but I think you are right that we can start with alert for when the whole disk starts to run out, [which we already have](https://github.com/m-lab/prometheus-support/blob/master/config/federation/prometheus/alerts.yml#L1040).

For getting rid of the synthetic metrics for collectd and vdlimit while also avoiding alerts for migrated nodes, I think I can just add an additional criteria that excludes nodes that have metrics which only exist on the platform cluster.

**Comment by nkinkade** [comment]
This was resolved by PR #506 referenced above. We no longer use synthetic node_exporter metrics to avoid alerts.
