### ISSUE TITLE
Pod network connection failures after create or recreate

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/k8s-support#127]
This is a place holder for a known issue with unknown cause.

We've observed pod networking sometimes result in initial-connection failures. For containers like NDT after the pod reports "Ready", this has manifested as:

* Failing to connected to TLS port
* After connecting, tests failing immediately with NaN/NaN.
* Subsequent normal behavior.

This may be an artifact of k8s, coreos, multus, or something else.

**Comment by stephen-soltesz** [comment]
This is still an outstanding issue. Observed again tonight.

**Comment by nkinkade** [comment]
@stephen-soltesz: Is this still an issue? If it is, I'm not aware of it.

**Comment by stephen-soltesz** [comment]
I now suspect this was caused by the javascript bug in our default client. I agree this is not still an issue.
