### ISSUE TITLE
Missing daemonsets should cause alerts to fire on staging cluster

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/k8s-support#142]
Recently, when trying to deploy the new version of ndt-server to the staging cluster (before testing in sandbox) we accidentally left the cluster in a bad state with most daemonsets missing. However, no alerts fired due to this condition. We should have alerts that fire.

**Comment by nkinkade** [comment]
m-lab/prometheus-support#420 in conjunction with #153 should have resolved this problem, at least for most DaemonSets that are currently running and mostly stable. We will need to add additional alerts for other DaemonSets as they come online (e.g., scamper).

**Comment by nkinkade** [comment]
I think this issue is safe to close.
