### ISSUE TITLE
Configure the network interface on k8s platform nodes with ethtool or similar.

### ISSUE THREAD

**Issue by nkinkade** [m-lab/k8s-support#159]
On the old platform we used `ethtool` to configure various low-level network interface parameters:

https://github.com/m-lab/nodebase-private/blob/master/support/setup_ethtool

In chatting with @mattmathis, we probably need to be doing this on our platform CoreOS nodes too.

Questions:
* Are we already doing this somehow in the epoxy-image when node images are created?
* If not, `ethtool` is not apparently part of CoreOS, so we'd need to find another way.

**Comment by nkinkade** [comment]
Removed myself from this issue and added @pboothe, who will follow up with @mattmathis about this question.

**Comment by evfirerob** [comment]
I'm not sure whether it was introduced by a later CoreOS version update or it's installed manually somewhere, but `ethtool` is available now.

I have experimented with the networkd-specific way of disabling TCP Segmentation Offload but according to the [documentation](https://systemd.network/systemd.link.html) and to my tests, it seems that networkd can either enable TSO or set it to the "kernel default" but there's no option to explicitly disable it.

I'm testing with `ethtool` as part of the [generate_network_config.sh](https://github.com/m-lab/epoxy-images/blob/sandbox-roberto-set-tco/configs/stage3_coreos/resources/generate_network_config.sh#L45) script in epoxy-images.

**Comment by nkinkade** [comment]
A lot more than just TSO is currently being configured via `ethtool` on the legacy platform. Was it determined somewhere that all those other settings are no longer needed and that TSO is the only configuration we care about going forward? If so, then good.

**Comment by evfirerob** [comment]
I was following https://docs.google.com/document/d/128e27XB5GcuOef04yU6pNRGhWQ_ekKMAgDgyqSyFrGk/edit# where [@Stephen Soltesz] (I believe) summarized the configurations to apply to switches and nodes.

If there's a longer list somewhere I'm happy to look at that and maybe unify all of those settings into a single script.

**Comment by nkinkade** [comment]
The longer list is linked to in the first post of this issue.

I just want to be sure that we are explicitly making the decision to not carry forward setting things like `gso`, `gro`, `ufo`, `lro`, etc.... all the settings in the file linked to. The document you're referring to explicitly calls for turning of `tso`, but is quiet on all the other settings we are currently making. @pboothe  was supposed to take over this issue, following up with @mattmathis.

**Comment by stephen-soltesz** [comment]
Unless we have extraordinarily good reasons, I'd like us to rely on default settings where possible. Preliminary results from the new stack show improved performance with the current settings on the canary mlab3.lga03 and mlab3.lax02 nodes.

**Comment by nkinkade** [comment]
@stephen-soltesz: Would you close this issue if you believe it is now resolved by the m-lab/epoxy-images#124?

**Comment by stephen-soltesz** [comment]
@pboothe or @mattmathis Please provide a specific reason to include any of the other ethool settings or, we'll close this issue by EOW.

**Comment by evfirerob** [comment]
@nkinkade: I see your point. I'm going to edit the PR description to unlink it from this issue as it's not obvious that merging it is enough, then we can keep this one open independently.

My bad, I incorrectly assumed that configuration had been superseded by @stephen-soltesz 's document, and this issue had been already discussed on a separate channel since both have been around for a while. Sorry about that.
