### ISSUE TITLE
Scraping etcd with Prometheus requires complicated client TLS certificate and key authentication

### ISSUE THREAD

**Issue by nkinkade** [m-lab/k8s-support#176]
Scraping etcd with Prometheus requires Prometheus to authenticate with a client/peer TLS certificate and key.  By default etcd is started with the flag `--client-cert-auth=true`, which enables TLS authentication for clients. This is all good and well, but is overly complex for the purposes of simply scraping metrics over the VPC network. etcd should somehow support enabling scraping metrics endpoints on a private interface without having to resort to TLS authentication.

@stephen-soltesz found this for a newer version of etcd:

https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/monitoring.md#health-check

However, it's unclear in that whether this will expose anything other than basic health check data.

**Comment by pboothe** [comment]
Priority could (and should!) rise once we start running more recent version of etcd.
