### ISSUE TITLE
Update fluentd container and enable systemd logging

### ISSUE THREAD

**Issue by robertodauria** [m-lab/k8s-support#177]
Fluentd doesn't currently read systemd logs.

The version we are using is very old (2014), libsystemd on the host is much newer and wants a more recent version of glibc than the one included in the container. To enable systemd logging we need to update fluentd.

**Comment by nkinkade** [comment]
@robertodauria: Is this issue still valid, or was it resolved? I feel you at some point updated the version of fluentd, but am not sure whether this issue got resolved or remains open?

**Comment by nkinkade** [comment]
@robertodauria: Is this issue still valid. It seems like perhaps this issue could be closed and superseded by #233?

**Comment by robertodauria** [comment]
I think closing this issue is the right thing to do, since at this point fluentd has been updated and it's happily forwarding logs from systemd services.

Thank you for going through the backlog and keeping it up-to-date!
