### ISSUE TITLE
The configuration for nodeinfo should not be used to construct its pusher instance.

### ISSUE THREAD

**Issue by pboothe** [m-lab/k8s-support#220]
Once https://github.com/m-lab/pusher/issues/61 is resolved, eliminate the dependency between the nodeinfo daemonset config and the contents of the nodeinfo ConfigMap

**Comment by nkinkade** [comment]
@pboothe: Can you elaborate on the reasoning behind this issue? Do you mean that the `--datatype` flag for pusher should be removed, and that pusher should just automatically upload any datatype (i.e., subdirectory) it finds in a particular configured data directory?

As I understand it, right now, pusher accepts an [arbitrary number of `--datatype` flags](https://github.com/m-lab/k8s-support/blob/master/k8s/daemonsets/templates.jsonnet#L159). It will only upload data from a subdirectory that was passed  as a `--datatype` flag. On the surface this seem not unreasonable to me, to allow for directories to exist in the data directory for which we don't push data.

This also begins to look like an issue that should filed in the pusher repo, not in the k8s-support directory.

Could you help clarify this for me?

**Comment by pboothe** [comment]
Back in the day, before configmaps were immutable, it was a really worrying thing to have pusher read the same configmap as nodeinfo - the configmap could change at any time, and it was not clear what the right thing to do was for pusher when it did.  Now that configmaps are immutable, it is a lot less worrying.
