### ISSUE TITLE
the three k8s-master VMs should upgrade themselves regularly

### ISSUE THREAD

**Issue by pboothe** [m-lab/k8s-support#27]
One on Monday, the next on Tuesday, and the next on Wednesday.

`kubeadm upgrade` is the command of interest.

**Comment by nkinkade** [comment]
This is an old issue, and not quite correct, but it's close enough that I'm taking it over for the work being done to automate master node OS upgrades.

**Comment by nkinkade** [comment]
We believe that OS update are now going to be handled by CLUO, which is deployed to both sandbox and staging. We are currently waiting for the machines to actually need an upgrade to verify that this is actually going to work as intended.  Meanwhile, I have synthetically flagged staging master `k8s-platform-master-us-central1-b` as needing a reboot for an upgrade (using `locksmitchctl send-node-reboot`)... and manually set the reboot window for Friday 15:00-17:00 UTC. This node should reboot tomorrow in that window. If it does, then we can be pretty sure this is all working as intended.
