### ISSUE TITLE
The code that sets up stuff in /etc should be moved to epoxy-images

### ISSUE THREAD

**Issue by pboothe** [m-lab/k8s-support#29]
This is a TODO, because the support for building /etc is not working and in flux, so we are leaving things in the old bad state for a while.  The code in question is in `node_k8s_setup.sh`

**Comment by nkinkade** [comment]
@pboothe: Is it still the current thinking that [all filesystem modifications](https://github.com/m-lab/k8s-support/blob/master/node/setup_k8s.sh.template#L42)  [to a node's /etc directory](https://github.com/m-lab/k8s-support/blob/master/node/setup_k8s.sh.template#L53) should be moved out of the setup_k8s.sh script and be baked into images created by epoxy-images? If so, then I'd like to make this change in the next week or so.

**Comment by nkinkade** [comment]
I believe this is mostly done, now that we have migrated fully to Ubuntu:

https://github.com/m-lab/k8s-support/blob/master/node/setup_k8s.sh.template#L47

Verify this and close as necessary. Assigning to myself.
