### ISSUE TITLE
/proc/sys/kernel/pid_max currently set to 32768

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/k8s-support#345]
The consequence of this is that PID leaks in containers make the entire system unmanageable.

If possible, this limit should be applied per-container so that the root context does not become unmanageable as a result of individual container behavior.

**Comment by stephen-soltesz** [comment]
Typical signature of a pid leak, capping out at ~30k:

![30k-pids](https://user-images.githubusercontent.com/1085316/71482530-07290b80-27d1-11ea-9363-ace673f850b1.png)

**Comment by stephen-soltesz** [comment]
Connected to https://github.com/m-lab/traceroute-caller/issues/50

**Comment by stephen-soltesz** [comment]
SupportPodPidsLimit - available in k8s v1.14 as beta feature default available. Parameter passed to node kubelet?
https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#overview

**Comment by pboothe** [comment]
Desired solution is to turn on per-container PID limits (if possible). That should reduce the "blast radius" for bad containers.

**Comment by nkinkade** [comment]
Looks like things have changed since we migrated to Ubuntu. From two random production Ubuntu nodes:
```
mlab@mlab2-den04:~$ cat /proc/sys/kernel/pid_max 
4194304

mlab@mlab1-svg01:~$ cat /proc/sys/kernel/pid_max 
4194304
```
Looks like the new default max on our Ubuntu nodes is now **4,194,304**.  It feels like that number could easily obviate the need for this issue. A pid leak that fills up more than 4 million slots would have to be so severe that it should probably take the whole node down anyway.

@stephen-soltesz: Can this issue be closed?

**Comment by stephen-soltesz** [comment]
@nkinkade are per-container PID limits a possibility?

We don't want a single container to be able to take the whole system down.

**Comment by nkinkade** [comment]
@stephen-soltesz: It appears that this can be achieved through a kubelet setting `PodPidsLimit`:

https://godoc.org/k8s.io/kubernetes/pkg/kubelet/apis/config#KubeletConfiguration

> // The maximum number of processes per pod.  If -1, the kubelet defaults to the node allocatable pid capacity.
> PodPidsLimit int64

It appears that kubeadm's `[KubeletConfiguration](https://godoc.org/k8s.io/kubelet/config/v1beta1#KubeletConfiguration)` supports this option, which means we could add it to our [kubeadm template config](https://github.com/m-lab/k8s-support/blob/master/manage-cluster/kubeadm-config.yml.template#L48).

What is a reasonable limit?

**Comment by stephen-soltesz** [comment]
The old coreos limit wouldn't be a bad starting point -- 32768 ?

In practice we see pid counts from traceroute-caller in the 2-3K's. I wouldn't object to 10k. That seems wildly high.

**Comment by stephen-soltesz** [comment]
Sorry, I'm forgetting that our monitoring only provides whole-node PID counts. I _believe_ the high PID counts are a result of traceroute-caller's many background processes. We see similar counts from goroutines which are directly attributable to TC.
