### ISSUE TITLE
The fluentd kubernetes_metadata plugin floods the API server

### ISSUE THREAD

**Issue by robertodauria** [m-lab/k8s-support#365]
Yesterday we encountered an issue where fluentd was crashing a few seconds after starting up due to memory limits (`800Mi`) being hit.

At the same time, there was a flood of requests to the API server from every node on the platform which generated a heavy load on the master nodes, made them slow down significantly and triggered the `PlatformCluster_EtcdMemberCommunicationTooSlow` alert.

Temporarily deleting the fluentd DaemonSet cleared the alert. Subsequent testing on a single node showed that the sudden memory spike depended on the `kubernetes_metadata` plugin being enabled, which is also consistent with what we observed on the apiserver - the plugin contacts the apiserver at startup time and it's the only fluentd component interacting with Kubernetes.

The kubernetes_metadata plugin has now been disabled entirely.

Since k8s metadata on log messages is something we want, though, we should investigate this more and test the most recent version of the plugin to see if the problem went away.

**Comment by pboothe** [comment]
It looks like a fix for something related went in in https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/pull/189, which was part of 2.4.0

So I would expect that 2.4.1 (which is the current "most recent" release) either fixes the problem, or the problem remains unfixed.  That said, it looks like their unit tests currently fail (and have done so for a while) and nobody cares enough to fix them, which is a worrying sign from a "code health" perspective.

**Comment by nkinkade** [comment]
Closing this because we no longer use Fluentd, but have switched to Vector from timber.io instead.
