### ISSUE TITLE
Delete measurementlab/neubot dockerhub repo

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/k8s-support#368]
After https://github.com/m-lab/k8s-support/pull/367 is deployed to production, we should eliminate the `measurementlab/neubot` repo in dockerhub. The upstream repo is neubot/dash -- the M-Lab fork is m-lab/dash, and the dockerhub repo should be measurementlab/dash -- which it is now.

**Comment by nkinkade** [comment]
@stephen-soltesz: It looks like #367 was merged. Does that mean that someone can delete the measurementlab/neubot DockerHub repo and close this issue?

**Comment by stephen-soltesz** [comment]
@nkinkade Yeah, go ahead and delete it. Or, assign to me so I can.

**Comment by nkinkade** [comment]
Deleted. I also noticed that there is a `measurementlab/neubot-dash` repo and also a `measurementlab/dash` repo. Should the former also be deleted?

**Comment by stephen-soltesz** [comment]
Yes, please. We only want the measurementlab/dash repo + image.

**Comment by nkinkade** [comment]
Done. `measurementlab/neubot-dash` is also deleted.
