### ISSUE TITLE
Revtr blockers

### ISSUE THREAD

**Issue by pboothe** [m-lab/k8s-support#401]
- [ ] Use less RAM for unneeded sidecar services (@pboothe on this)
- [ ] Get privacy questions filled in (revtr team has to do this)
- [ ] Get the data from the master system (we need to figure this out jointly between M-Lab and revtr folks)

**Comment by nkinkade** [comment]
@stephen-soltesz: To the best of your knowledge is this issue resolved? I would imagine so, since revtr is running on the platform.

**Comment by stephen-soltesz** [comment]
The third item is in progress. but, we're tracking that in the roadmap & milestone docs now. We can close this issue.
