### ISSUE TITLE
Replace Container Linux Update Operator

### ISSUE THREAD

**Issue by nkinkade** [m-lab/k8s-support#418]
The Container Linux Update Operator is designed to run on Container Linux, which was EOLed. We are switching to Ubuntu, and have figured out a way to keep it running under Ubuntu for now, but it should be replaced with something else.

One possibility would be to cherry pick parts of CLUO that do what we want, and leave all the rest behind, effectively creating a new service to manage rolling reboots of the platform.

**Comment by pboothe** [comment]
This functionality is only used for rolling reboots

**Comment by nkinkade** [comment]
Superseded by #455.
