### ISSUE TITLE
Make sure IP is created

### ISSUE THREAD

**Issue by pboothe** [m-lab/k8s-support#44]
e.g. k8s-master-ip

**Comment by nkinkade** [comment]
@pboothe: Could you elaborate the purpose of this issue?

**Comment by pboothe** [comment]
To make sure that the IP addresses for the master machines have been created within Google Cloud.  That way, setup of master nodes won't fail because those IPs have not (yet) been set up.

It is not impossible that your work has rendered this issue obsolete.

**Comment by nkinkade** [comment]
@pboothe: I believe this is all adequately handled by the cluster bootstrap script now:

https://github.com/m-lab/k8s-support/blob/master/manage-cluster/bootstraplib.sh#L13

And it even makes sure that DNS entries exist, should we need them for anything:

https://github.com/m-lab/k8s-support/blob/master/manage-cluster/bootstraplib.sh#L30

If you believe the links I shared above demonstrate that the requirements of this issue are fulfilled, would you close this issue?

**Comment by pboothe** [comment]
Woohoo!
