### ISSUE TITLE
Docker sometimes cannot create new containers

### ISSUE THREAD

**Issue by nkinkade** [m-lab/k8s-support#468]
Today I noticed a spike in "Probable Container OOMs" on 7 machines, occurring all at roughly the same time

![Screenshot from 2020-07-21 16-29-15](https://user-images.githubusercontent.com/1392825/88113655-72706b80-cb6f-11ea-8ec1-0549bff07aa2.png)

Spot checking 3 of them (mlab1-sea07, mlab2-lga08, mlab1-bom02), I found a similar issue at all 3. The "probable ooms" appear to be coming from error messages like the following:

```
Jul 21 16:45:06 mlab1-bom02.mlab-oti.measurement-lab.org kernel: INFO: task modprobe:691389 blocked for more than 120 seconds.
Jul 21 16:45:06 mlab1-bom02.mlab-oti.measurement-lab.org kernel:       Tainted: G        W         5.4.0-26-generic #30-Ubuntu
Jul 21 16:45:06 mlab1-bom02.mlab-oti.measurement-lab.org kernel: "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
```

These processes are running on the affected machines, apparently in some I/O wait status indefinitely:

```
root      691386  0.0  0.0   4372  1088 ?        D    16:43   0:00 iptables -w 5 -N KUBE-PROXY-CANARY -t mangle
root      691389  0.0  0.0   8816  1532 ?        D    16:43   0:00 /sbin/modprobe -q -- iptable_mangle
```

It appears that modprobe is stuck for some reason, though the `iptable_mangle` module is apparently loaded, at least according to `lsmod`.

The logs are also filled with message like this one:

```
unregister_netdevice: waiting for lo to become free. Usage count = 1
```

When attempting to run the command `docker run --rm -ti busybox /bin/sh`, the command/terminal hangs and has to be forcefully closed. That same command works fine on an unaffected machine.

**Comment by nkinkade** [comment]
On affected machines, there also appears to be a `kworker` process hung in some I/O wait status:

```
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           9  0.0  0.0      0     0 ?        D    Jun26   6:36 [kworker/u64:0+netns]
```

**Comment by nkinkade** [comment]
Put all affected machines into GMX mode:

/machine mlab2-bom02
/machine mlab1-sea07
/machine mlab1-bom02
/machine mlab2-lga08
/machine mlab1-nuq04
/machine mlab2-prg03
/machine mlab3-maa01

**Comment by stephen-soltesz** [comment]
The set of metros included in the recent ndt7 usage spikes (to see if it's correlated):
<img width="1706" alt="Screen Shot 2020-07-21 at 7 19 14 PM" src="https://user-images.githubusercontent.com/1085316/88116697-2e896080-cb87-11ea-88e4-c91565def754.png">

**Comment by nkinkade** [comment]
Thank you for adding this. It appears that there is only overlap for 2 of the 7 metros (sea and lga), which doesn't seem like a strong correction, at least at first glance.

**Comment by nkinkade** [comment]
Another interesting thing worth noting is that the error `unregister_netdevice: waiting for lo to become free. Usage count = 1` appears a good deal before the "modprobe blocked" messages. For example, on mlab2-prg03 the first instance of that message was:

```
Jun 30 18:51:38 mlab2-prg03.mlab-oti.measurement-lab.org kernel: unregister_netdevice: waiting for lo to become free. Usage count = 1
```

... which is weeks before we noticed anything yesterday. It is not impossible that the true problems began much earlier and we only noticed them yesterday due to the dmesg_exporter messages.

**Comment by nkinkade** [comment]
Since I upgraded the API cluster to 1.17.8 yesterday around 16:30, and all of these machines exhibited this issue within the next hour, it is not unreasonable to hypothesize that it had something to do with the upgrade to the API cluster, and was therefore ephemeral.

I'm going to reboot 4 of the 7 affected machines, leaving 3 in GMX, and we'll see if this problem presents itself again. If it doesn't present again in the next week or two, then we should close this issue.

The machines I will reinstate are:

mlab1-sea07
mlab1-bom02
mlab3-maa01
mlab2-lga08

... which will leave these in GMX until further notice:

mlab2-bom02
malb1-nuq04
mlab2-prg03

**Comment by nkinkade** [comment]
It was decided that this event was most likely in some way related to me having upgraded the API cluster to k8s 1.17.8, since these events all occurred within an hour or two after the upgrade, and no other similar issues like this arose after. It only appeared to affect this set of 7 machines. Closing this issue  until we have evidence that it is still happened and was not some freak result of the API cluster upgrade.
