### ISSUE TITLE
Unclean shutdown of tcp-info can leave tcpevents.sock, causing tcp-info to not be able to start

### ISSUE THREAD

**Issue by nkinkade** [m-lab/k8s-support#492]
On mlab3-mnl01 there was a large load spike, which, among other things, caused tcp-info in the ndt pod to be oom-killed. After this happened, the tcp-info container was no longer able to start with error:

`2020/09/15 17:15:44 main.go:101: Could not listen on%!(EXTRA string=/var/local/tcpinfoeventsocket/tcpevents.sock) (error: listen unix /var/local/tcpinfoeventsocket/tcpevents.sock: bind: address already in use)`

There are 4 files on the host machine:

```
root@mlab3-mnl01:/home/mlab# find /var/lib -name tcpevents.sock
/var/lib/kubelet/pods/1b5c8c51-ab78-40ca-b8eb-0915e7e69cc8/volumes/kubernetes.io~empty-dir/tcpinfoeventsocket/tcpevents.sock
/var/lib/kubelet/pods/41d7b67d-6f89-4fd3-be0f-4e7243ccceb9/volumes/kubernetes.io~empty-dir/tcpinfoeventsocket/tcpevents.sock
/var/lib/kubelet/pods/58479a91-729a-4cfd-b592-f9a12340f893/volumes/kubernetes.io~empty-dir/tcpinfoeventsocket/tcpevents.sock
/var/lib/kubelet/pods/f530be48-4bc3-4937-8caa-40b2a967aa06/volumes/kubernetes.io~empty-dir/tcpinfoeventsocket/tcpevents.sock
```

Looking at the pod in question, it appears that the file `tcpevents.sock` still exists in the `EmptyDir` directory in the host context, preventing tcp-info from starting:

```
nkinkade@npk-p52:~$ kubeoti get pods -l workload=ndt -o wide | grep mlab3-mnl01
ndt-49fp4   11/12   CrashLoopBackOff   58         5h4m    192.168.132.205   mlab3-mnl01.mlab-oti.measurement-lab.org   <none>           <none>
nkinkade@npk-p52:~$ kubeoti get pod --no-headers -o custom-columns=wwn:metadata.uid ndt-49fp4
41d7b67d-6f89-4fd3-be0f-4e7243ccceb9
```

A manual fix is to delete the pod, which deleted the underlying `EmptyDir` directory in the host context, getting rid of the stale socket file.

What is the longer term solution?

**Comment by stephen-soltesz** [comment]
@nkinkade the uuid-annotator had a similar issue with it's listen socket. https://github.com/m-lab/uuid-annotator/pull/35 unconditionally removing the socket before creating it appeared to work. IIUC, the tcpinfo crash would have caused the other listening containers (traceroute-caller, pcap, uuid-annotator) to be disconnected (and try to reconnect somehow, possibly by restarting). It's possible that the recovery could be awkward -- e.g. k8s restarts everything before tcpinfo recreates the socket, but it ought to work out after a few tries.
