### ISSUE TITLE
If unattended-upgrades upgrades containerd, dockerd gets shut down with no restart

### ISSUE THREAD

**Issue by nkinkade** [m-lab/k8s-support#520]
Early this morning unattended-upgrades updated the containerd package on almost every api-server in every GCP project. The update process stopped the Docker daemon, but never restarted it, [which is apparently a known bug (waiting for a fix?)](https://bugs.launchpad.net/ubuntu/+source/containerd/+bug/1870514).

This is fairly serious because it entire took down the staging and sandbox API cluster, and took down all but a single production API server (all key API components run in Docker containers).

While this bug will hopefully receive a fix, we may want to consider telling unattended-upgrades to not upgrade containerd. One the one hand, this should prevent this from happening again, while on the other it means containerd will not receive security updates without manual intervention from an operator.

**Comment by laiyi-ohlsen** [comment]
Moving away from Docker soon @nkinkade to add more info

**Comment by nkinkade** [comment]
We plan to migrate away from Docker in the not-distant future, so have decided to not worry about this issue for now:

https://github.com/m-lab/k8s-support/issues/523
