### ISSUE TITLE
Upgrade k8s in platform clusters to 1.19.x

### ISSUE THREAD

**Issue by nkinkade** [m-lab/k8s-support#583]
1.21.x has already been out for a while now, and 1.22.x is already in beta. In order to not fall too far behind we should upgrade the clusters to the latest release of 1.19.x.

**Comment by nkinkade** [comment]
@stephen-soltesz, @robertodauria: I've added you both to this issue, because one or both of you should probably be the ones to do this upgrade. Or we can more or less do it all together on a VC in sandbox, then someone else could do staging and then another person could do production?

**Comment by stephen-soltesz** [comment]
That's a good idea. I'd like to do at least one of the clusters.

**Comment by nkinkade** [comment]
One thing we should verify on upgrade is that all control-plane and client certificates get renewed automatically by the k8s upgrade process. [The documentation](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/#automatic-certificate-renewal) says:

```
kubeadm renews all the certificates during control plane upgrade. [...] This feature is designed for addressing the simplest use cases;
```

... but we should manually verify that this is happening.

**Comment by nkinkade** [comment]
This was completed quite some time ago. We are now already running 1.20.x. Closing.
