### ISSUE TITLE
Create k8s config to run fast-SS as a daemon-set

### ISSUE THREAD

**Issue by gfr10598** [m-lab/k8s-support#64]

**Comment by nkinkade** [comment]
@gfr10598: I believe this 7-month-old issue is now no longer relevant, correct? My understanding is that fast-SS will now (is, actually) deployed as a sidecar container in the pod that it is measuring. If this is correct, then could you please close this issue?

**Comment by nkinkade** [comment]
Commented-and-closed by accident, when I just meant to comment. Reopening for review by @gfr10598.

**Comment by pboothe** [comment]
Correct, closing
