### ISSUE TITLE
Write scripts to start up services on the node

### ISSUE THREAD

**Issue by kokosta** [m-lab/k8s-support#8]

**Comment by pboothe** [comment]
V.demo is complete thanks to #15

**Comment by nkinkade** [comment]
What sort of services? Will we be using systemd services for most of things?

**Comment by pboothe** [comment]
This is the bug for the script that is called by ePoxy (the ePoxy "action") after boot. The proper balance between systemd configs and the ePoxy action is still being figured out.

**Comment by pboothe** [comment]
Done - #15 #19 #21 and #23 close this out. The node joins the cluster after boot. There's remaining work about making sure everything is just right and better designed, but this issue feels done-for-now to me.
