### ISSUE TITLE
Guarantee that experiment containers cannot interfere with sidecar generated data

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/k8s-support#99]
We expect to deploy experiment daemonsets with multiple containers, each generating their own datatypes to local disk before upload by pusher. In all cases, we want strong isolation between the primary experiment container and all supporting containers so that the experiment can never interfere with other data collection.

**Comment by nkinkade** [comment]
@stephen-soltesz: Are the k8s `VolumeMount`s that are in place for each container in a pod not strong enough isolation?

**Comment by stephen-soltesz** [comment]
When I exec into the ndt container, I can access the dirs containing the tcpinfo and traceroute data. I could remove files if I wanted to. I think this is a mistake once we start putting third-party experiments on the platform too.

**Comment by nkinkade** [comment]
Perhaps each container should only mount a subdirectory of the data directory for the experiment (the container's datatype dirs), with the exception of pusher? What do you think? Flagging @pboothe for his input here too.

**Comment by pboothe** [comment]
Nothing (not even pusher) should mount `/var/spool/ndt`.  Instead, each container should mount zero or more datatypes as needed.

**Comment by pboothe** [comment]
This fix for this is to add one volume per datatype to templates.jsonnet

**Comment by nkinkade** [comment]
@pboothe: Thanks. As a resolution to this issue, I'll go through our DaemonSets to be sure that none of them mount the root experiment data directory, as they currently all do, but only the datatype subdirectories they are responsible for. Pusher will be the only container to mount the root experiment directory. If this all sounds right, then no need to reply, and a PR will be forthcoming. If not, clarify as necessary.

**Comment by nkinkade** [comment]
Hmm. Actually, this is the way things used to work, but I made a PR in the past that intentionally changed this:

https://github.com/m-lab/k8s-support/pull/231

@stephen-soltesz: Does this mean that that PR, the content of which you and I both agreed on, at least at the time, was fundamentally contrary to the intention behind this issue?

**Comment by stephen-soltesz** [comment]
The goal of #231 was to simplify the mount logic to help the host experiment shutdown cleanly. Do you still believe that the mount orchestration is possibly contributing to that problem? If not, we could restore it. If so, we can cordon the core service data with a similar (but still less complex) config.

**Comment by nkinkade** [comment]
If I recall, the main motivation of the PR was simplify and reduce the Volume and VolumeMount configurations for each pod, especially the host experiment (which had around 15 separate volumes and mounts). We had an outside hope that _maybe_ the wedged `host` pod bug had something to do with all the volumes and mounts, but the bug persisted, even after #231 was merged.  So #231 did simplify volumes and mounts, but also apparently reduced the filesystem isolation of each container.

So is the thinking that we now want to essentially revert #231?

**Comment by stephen-soltesz** [comment]
Our goal is to keep things working, with as simple a config as possible, and strong isolation between core & experiment data. How close can we get to that?

**Comment by nkinkade** [comment]
To get the container filesystem isolation this issue is pointing at, we'd need to revert #231. The main experiment which this complicates is the `host` experiment which has around a dozen datatypes.

**Comment by stephen-soltesz** [comment]
Can we use a different mount strategy for host & experiments?

**Comment by nkinkade** [comment]
Maybe. The host "experiment" is a core DaemonSet, 100% managed by us, not a 3rd party experiment. Is it okay for the `host` pod to not have the same isolation we require for regular experiments?

**Comment by nkinkade** [comment]
I believe this issue is resolved by merged PR #353. Closing.
